### ISSUE TITLE
Setup Github Actions for testing

### ISSUE THREAD

**Issue by arthexis** [arthexis/sigils#7]
Configure Github Actions / pytest / tox to accomplish the following goals:
- Ensure all tests are run automatically on push (check https://github.com/ymyzk/tox-gh-actions)
- The following python versions are supported: 3.9, 3.10, 3.11
- The following OS matrix is used: Ubuntu LTS, Windows 
- Track test coverage 
- See what badges we can add to show the coverage and passing CI/CD
- Rename master "master" to "main"

**Comment by klaymond** [comment]
Tests are successfully running automatically in branch automated-testing. They are erroring out with a type error. In order to close this issue we would need to test on a stable version:
 ```
 C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\importlib\__init__.py:127: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  <frozen importlib._bootstrap>:1030: in _gcd_import
      ???
  <frozen importlib._bootstrap>:1007: in _find_and_load
      ???
  <frozen importlib._bootstrap>:972: in _find_and_load_unlocked
      ???
  <frozen importlib._bootstrap>:228: in _call_with_frames_removed
      ???
  <frozen importlib._bootstrap>:1030: in _gcd_import
      ???
  <frozen importlib._bootstrap>:1007: in _find_and_load
      ???
  <frozen importlib._bootstrap>:972: in _find_and_load_unlocked
      ???
  <frozen importlib._bootstrap>:228: in _call_with_frames_removed
      ???
  <frozen importlib._bootstrap>:1030: in _gcd_import
      ???
  <frozen importlib._bootstrap>:1007: in _find_and_load
      ???
  <frozen importlib._bootstrap>:986: in _find_and_load_unlocked
      ???
  <frozen importlib._bootstrap>:680: in _load_unlocked
      ???
  <frozen importlib._bootstrap_external>:850: in exec_module
      ???
  <frozen importlib._bootstrap>:228: in _call_with_frames_removed
      ???
  sigils\__init__.py:2: in <module>
      from .tools import *
  sigils\tools.py:122: in <module>
      sigils: tuple[str] | list[str],
```
I will keep working on the other tasks in this issue.

**Comment by arthexis** [comment]
I remove the automated tests for now, since the new test suite is much shorter and can just be run locally in a second, will consider something more complex as we move into more difficult use cases
